# Generated by Django 3.1.1 on 2020-09-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200915_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Color', 'Color'), ('Size', 'Size'), ('Size-Color', 'Size-Color')], default='None', max_length=20),
        ),
    ]
